server:
  port: 7070

spring:
  application:
    name: servicio_configuracion
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Moises-Mestas/AquiNomas2.git
          searchPaths: Backend/config-data
          default-label: moises
  security:
    user:
      name: root
      password: 123456
