server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #========servicio auth=======#
        - id: servicio-auth
          uri: lb://servicio-auth
          predicates:
            - Path=/auth/**
        #========servicio cliente=======#
        - id: servicio-cliente
          uri: lb://servicio-cliente
          predicates:
            - Path=/clientes/**, /administradores/**
          filters:
            - AuthFilter
        #========servicio reportes=======#
        - id: servicio-reportes
          uri: lb://servicio-reportes
          predicates:
            - Path=/reportes/**